pub enum Instr {
    Cls,
    Ret,
    Sys(u16),
    Jp(u16),
    Call(u16),
    SeVxKK(usize, u8),
    SneVxKK(usize, u8),
    SeVxVy(usize, usize),
    SneVxVy(usize, usize),
    LdVxKK(usize, u8),
    AddVxKK(usize, u8),
    LdVxVy(usize, usize),
    OrVxVy(usize, usize),
    AndVxVy(usize, usize),
    XorVxVy(usize, usize),
    AddVxVy(usize, usize),
    SubVxVy(usize, usize),
    SubnVxVy(usize, usize),
    ShrVx(usize),
    ShlVx(usize),
    LdI(u16),
    JpV0(u16),
    RndVxKK(usize, u8),
    DrwVxVyN(usize, usize, usize),
    SkpVx(usize),
    SknpVx(usize),
    LdVxDT(usize),
    LdVxK(usize),
    LdDTVx(usize),
    LdSTVx(usize),
    AddIVx(usize),
    LdFVx(usize),
    LdBVx(usize),
    LdIVx(usize),
    LdVxI(usize),
}

impl Instr {
    pub fn from(opcode: u16) -> Instr {
        let nibbles = (
            ((opcode & 0xF000) >> 12) as u8,
            ((opcode & 0x0F00) >> 8) as u8,
            ((opcode & 0x00F0) >> 4) as u8,
            ((opcode & 0x000F) >> 0) as u8,
        );
        let nnn = opcode & 0x0FFF; // also called xyz
        let kk = (opcode & 0x00FF) as u8; // also called yz
        let x = nibbles.1 as usize;
        let y = nibbles.2 as usize;
        let n = nibbles.3 as usize;

        match nibbles {
            (0, 0, 0xE, 0) => Instr::Cls,
            (0, 0, 0xE, 0xE) => Instr::Ret,
            (0, _, _, _) => Instr::Sys(nnn),
            (1, _, _, _) => Instr::Jp(nnn),
            (2, _, _, _) => Instr::Call(nnn),
            (3, _, _, _) => Instr::SeVxKK(x, kk),
            (4, _, _, _) => Instr::SneVxKK(x, kk),
            (5, _, _, _) => Instr::SeVxVy(x, y),
            (6, _, _, _) => Instr::LdVxKK(x, kk),
            (7, _, _, _) => Instr::AddVxKK(x, kk),
            (8, _, _, 0) => Instr::LdVxVy(x, y),
            (8, _, _, 1) => Instr::OrVxVy(x, y),
            (8, _, _, 2) => Instr::AndVxVy(x, y),
            (8, _, _, 3) => Instr::XorVxVy(x, y),
            (8, _, _, 4) => Instr::AddVxVy(x, y),
            (8, _, _, 5) => Instr::SubVxVy(x, y),
            (8, _, _, 6) => Instr::ShrVx(x),
            (8, _, _, 7) => Instr::SubnVxVy(x, y),
            (8, _, _, 0xE) => Instr::ShlVx(x),
            (9, _, _, 0) => Instr::SneVxVy(x, y),
            (0xA, _, _, _) => Instr::LdI(nnn),
            (0xB, _, _, _) => Instr::JpV0(nnn),
            (0xC, _, _, _) => Instr::RndVxKK(x, kk),
            (0xD, _, _, _) => Instr::DrwVxVyN(x, y, n),
            (0xE, _, 9, 0xE) => Instr::SkpVx(x),
            (0xE, _, 0xA, 1) => Instr::SknpVx(x),
            (0xF, _, 0, 7) => Instr::LdVxDT(x),
            (0xF, _, 0, 0xA) => Instr::LdVxK(x),
            (0xF, _, 1, 5) => Instr::LdDTVx(x),
            (0xF, _, 1, 8) => Instr::LdSTVx(x),
            (0xF, _, 1, 0xE) => Instr::AddIVx(x),
            (0xF, _, 2, 9) => Instr::LdFVx(x),
            (0xF, _, 3, 3) => Instr::LdBVx(x),
            (0xF, _, 5, 5) => Instr::LdIVx(x),
            (0xF, _, 6, 5) => Instr::LdVxI(x),
            _ => unreachable!("unknown instruction"),
        }
    }
}
